#!/usr/bin/bash

# INSTALL SCRIPTS - SET TO LOCAL BIN


printf "\nInstalling...\n"

sudo cp dist/* /usr/local/bin
sleep 3

sudo apt update
sudo apt install expect -y

sleep 3

printf "\nDone.\n"
printf "type 'lmsbot' and [ENTER]\n"
