#!/usr/bin/bash

# AUTOMATIC LOGIN SCRIPT FOR WTC-LMS
# MAKES USE OF THE (EXPECT) LOGIN SCRIPT
# SCRIPT WILL KEEP LOGGING USER IN EVERY 4 HOURS WHILE PC TURNED ON AND SCRIPT IS RUNNING

while true; do
	echo ""
	echo "hello friend."
	echo""
	lms
	echo ""
	sleep 14400
	echo "token expired... logged out."
done
