#!/usr/bin/bash

# SCRIPT WITH MORE INTERACTION TO MAKE THE LMS LESS TEDIOUS
# SCRIPT MAKES USE OF ALL THE OTHER SCRIPTS
# LOGIN SCRIPT
# REVIEW SCRIPT
# GRADE SCRIPT
# DETAILS SCRIPT
# PROBLEMS SCRIPT
# LMS_HISTORY SCRIPT


printf "\nINTERACTIVE LMS 0.01\n"
echo "Hello friend."
read -p "What do you wanna do? " TODO

if [ $TODO == "login" ]; then
	lms

elif [ $TODO == "start" ]; then
	project-start

elif [ $TODO == "review" ]; then
	review

elif [ $TODO == "grade" ]; then
	grade

elif [ $TODO == "details" ]; then
	details

elif [ $TODO == "topics" ] || [ $TODO == "problems" ]; then
	problems

elif [ $TODO == "history" ]; then
	project-history
fi
